"""add_messages_user_id_created_at_index

Revision ID: 51284b34f287
Revises: 62fbe9dd3b5a
Create Date: 2026-09-08 21:54:10.599612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51284b34f287'
down_revision: Union[str, Sequence[str], None] = '62fbe9dd3b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_user_id_created_at', 'messages', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_user_id_created_at', table_name='messages')
    # ### end Alembic commands ###
