"""create_message_analyses_table

Revision ID: ea36927a8e80
Revises: 71471d157002
Create Date: 2026-09-08 19:19:37.057043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea36927a8e80'
down_revision: Union[str, Sequence[str], None] = '71471d157002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_analyses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('civility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('score_version', sa.String(length=50), server_default='1.0.0', nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=False),
    sa.Column('is_toxic', sa.Boolean(), nullable=False),
    sa.Column('hate_speech_score', sa.Float(), nullable=False),
    sa.Column('is_hate_speech', sa.Boolean(), nullable=False),
    sa.Column('hate_speech_label', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('llm_is_problematic', sa.Boolean(), nullable=True),
    sa.Column('llm_sentiment', sa.String(length=50), nullable=True),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('num_tokens', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_analyses_analyzed_at'), 'message_analyses', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_message_analyses_civility_score'), 'message_analyses', ['civility_score'], unique=False)
    op.create_index(op.f('ix_message_analyses_message_id'), 'message_analyses', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_analyses_message_id'), table_name='message_analyses')
    op.drop_index(op.f('ix_message_analyses_civility_score'), table_name='message_analyses')
    op.drop_index(op.f('ix_message_analyses_analyzed_at'), table_name='message_analyses')
    op.drop_table('message_analyses')
    # ### end Alembic commands ###
